### ISSUE TITLE
Support for BLT and BLT Project as SUT

### ISSUE THREAD

**Issue by danepowell** [acquia/orca#26]
**Proposed change**
When BLT is the SUT, copy blt-project from `/home/travis/build/acquia/blt/subtree-splits/blt-project` rather than installing it via `composer create-project` as we currently do here: https://github.com/acquia/orca/blob/develop/src/Fixture/FixtureCreator.php#L276

**Background**
BLT is a little unique as a system under test because it includes a [subtree split](https://github.com/acquia/blt/tree/10.x/subtree-splits/blt-project) for `acquia/blt-project`, which is used as a project template for the BLT itself as well as for ORCA's entire test fixture.

BLT and blt-project are loosely coupled but still need to be tested in unison, which is why we maintain blt-project as a subtree.

BLT's internal tests account for this by cloning the subtree split from within the current BLT working directory, rather than downloading it from https://github.com/acquia/blt-project via `composer create-project`. This ensures that any changes to blt-project play nicely with corresponding changes in the main blt repo.

The problem is that ORCA always gets blt-project via `composer create-project`, so it's not testing for these interactions, which recently caused a BLT PR to break: https://github.com/acquia/blt/pull/3648

@TravisCarden I'm happy to take a shot at fixing this but wanted to make sure to get your blessing first, and see if you have any guidance. It seems like it would require modifying FixtureCreator to carve out an exception when BLT is the SUT, I don't see how BLT could override this itself.

**Comment by TravisCarden** [comment]
Hi, @danepowell! Yes, BLT is definitely unique in this respect. I'm not opposed to solving the problem in ORCA itself, but I _do_ want to avoid special cases that could lead to test gaps and preserve my guiding design principle of using packages the way customers would. I have one idea which, if it works, would satisfy both goals _and_ be much simpler to implement. Namely, if you globally configure Composer in your Travis CI configuration with a [path repository](https://getcomposer.org/doc/05-repositories.md#path) pointing to `/home/travis/build/acquia/blt/subtree-splits/blt-project`, then if `composer create-project` respects custom repositories defined globally (I don't know if it does or not), ORCA should "just work" as it already is. (You might have to copy the `blt-project` subtree split outside the BLT clone so as to avoid a weird symlink within a symlink situation, but you get the picture.) Tell me if that's not clear. Otherwise, let me knowhow it turns out! 😃

**Comment by danepowell** [comment]
Awesome suggestion, that worked like a charm! It's a testament to ORCA's architecture how easy that was to accomplish.

**Comment by TravisCarden** [comment]
For posterity, here's the solution, from https://github.com/acquia/blt/pull/3648:

https://github.com/acquia/blt/blob/73783d67eeea7bb962e0be72f31b9454fef526bd/.travis.yml#L62-65
