### ISSUE TITLE
Improved Composer validation: ensure patched projects are version-locked

### ISSUE THREAD

**Issue by danepowell** [acquia/orca#39]
The recent spontaneous test failure was due to BLT applying a patch to phpcs-security-audit but not pinning phpcs-security-audit to the point release corresponding to the patch. When phpcs-security-audit released a new version, the patch no longer applied and all builds started failing.

I would consider it best practice that if a project applies patches via composer.json, it should also pin the corresponding version of the patched packages. A floating version constraint for a patched package is just begging for trouble.

This would be pretty straightforward to test for automatically.

The only problem is that some projects break this tenet intentionally, and somehow get away with it :smile:  https://github.com/acquia/lightning_core/blob/8.x-4.x/composer.json

**Comment by wimleers** [comment]
Also running into this at https://github.com/acquia/acquia_migrate/pull/114 … 😬

**Comment by TravisCarden** [comment]
The proposal makes sense on the face of it, @danepowell, but I'm afraid the consequences would be disastrous: Since some of our packages patch Drupal core, they would have to pin to an exact version, which would necessarily cause all `CORE_PREVIOUS`, `INTEGRATED_DEV`, and `CORE_NEXT` jobs to fail for everyone across the board. The moment any new version of core was released, the same would happen to the remaining jobs, too. Obviously, that's a show-stopper, and I don't readily perceive any way around it. I'm closing this issue "won't fix" on those grounds. By all means, point out any errors you perceive in my reasoning.

**Comment by danepowell** [comment]
I agree I don't know how to implement an automated test for a "best practice" that we intentionally break pretty regularly. If there's no obvious solution I guess it's fine to close this. There's certainly still a pain point here, I wonder if there's some other forum/product that should address it...
